import type { NextPage } from "next";
import Head from "next/head";
import { AppShell, NavLink } from "ui";

const navLinks: NavLink[] = [
  {
    label: "Home",
    path: "/",
  },
  {
    label: "Playlist",
    path: "http://localhost:3001/playlist",
  },
];

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell title="Movies" navLinks={navLinks}>
        <p>hello there</p>
      </AppShell>
    </div>
  );
};

export default Home;
