import type { NextPage } from "next";
import Head from "next/head";
import { useStore } from "store";
import { AppShell, NavLink } from "ui";
import MoviesContent from "../src/components/movies/MoviesContent";

const navLinks: NavLink[] = [
  {
    label: "Home",
    path: "/",
  },
  {
    label: "Playlist",
    path: "http://localhost:3001",
  },
];

const Home: NextPage = () => {
  const { movies } = useStore();
  console.log(movies);

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppShell title="Movies" navLinks={navLinks}>
        <MoviesContent />
      </AppShell>
    </div>
  );
};

export default Home;
